const List<String> skillCategories = [
  'Creative & Artistic Skills',
  'Tech & Programming',
  'Writing & Communication',
  'Music & Audio',
  'Performance & Entertainment',
  'Education & Knowledge Sharing',
  'Lifestyle & Wellness',
  'Entrepreneurial & Business Skills',
  'Other Useful & Unique Skills',
];

const Map<String, List<String>> subCategorySuggestions = {
  'Creative & Artistic Skills': [
    'Graphic Design',
    'UI/UX Design',
    'Digital Illustration',
    'Photography',
    'Videography',
    'Animation (2D/3D)',
    'Painting & Drawing',
    'Craft & DIY',
  ],
  'Tech & Programming': [
    'Web Development',
    'App Development',
    'Game Development',
    'Ethical Hacking & Cybersecurity',
    'Machine Learning & AI',
    'Blockchain & Web3',
    'Data Science & Analytics',
    'UI/UX Design',
  ],
  'Writing & Communication': [
    'Blogging',
    'Copywriting',
    'Storytelling / Fiction Writing',
    'Poetry',
    'Technical Writing',
    'Content Creation (Reels/Shorts + writing)',
    'Public Speaking',
  ],
  'Music & Audio': [
    'Singing',
    'Instrumental (Guitar, Piano, etc.)',
    'Music Production',
    'Beat Making',
    'Voice Acting',
    'Podcasting',
  ],
  'Performance & Entertainment': [
    'Acting / Drama',
    'Dance (Various styles)',
    'Comedy & Skits',
    'Magic / Illusions',
    'Influencer Vlogs',
  ],
  'Education & Knowledge Sharing': [
    'Teaching / Tutoring (Math, Science, etc.)',
    'Study Hacks / Productivity',
    'Book Summaries',
    'Career Tips & Guidance',
    'Motivational Talks',
  ],
  'Lifestyle & Wellness': [
    'Fitness & Bodybuilding',
    'Yoga & Meditation',
    'Diet & Nutrition',
    'Skincare & Beauty',
    'Mental Health',
  ],
  'Entrepreneurial & Business Skills': [
    'Business Strategy',
    'Startups & Pitches',
    'Stock Market / Crypto Analysis',
    'Finance & Budgeting',
    'Marketing / Branding',
    'Freelancing Tips',
  ],
  'Other Useful & Unique Skills': [
    'Cooking / Baking',
    'Gardening',
    'Travel & Exploration',
    'Pet Training / Care',
    'Interior Designing',
    'Life Hacks / DIY Fixes',
  ],
};
