// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-4J1yaf8VSPDJaypnYb4YxZJ5LIUu8TQ',
    appId: '1:370900926524:web:88c29ab30b550c7aa38339',
    messagingSenderId: '370900926524',
    projectId: 'tinkerly-a0709',
    authDomain: 'tinkerly-a0709.firebaseapp.com',
    storageBucket: 'tinkerly-a0709.firebasestorage.app',
    measurementId: 'G-RMQZCEPSP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAULg7nUS8im-MXQeYsvo3WNX15NDV4us',
    appId: '1:370900926524:android:42d2c66cbf20bafaa38339',
    messagingSenderId: '370900926524',
    projectId: 'tinkerly-a0709',
    storageBucket: 'tinkerly-a0709.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-4J1yaf8VSPDJaypnYb4YxZJ5LIUu8TQ',
    appId: '1:370900926524:web:8dea4d3a2d1a160aa38339',
    messagingSenderId: '370900926524',
    projectId: 'tinkerly-a0709',
    authDomain: 'tinkerly-a0709.firebaseapp.com',
    storageBucket: 'tinkerly-a0709.firebasestorage.app',
    measurementId: 'G-QX0QJEVNPR',
  );

}